name: Deploy to Strato

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install lftp -y

      - name: Deploy to Strato via SFTP
        env:
          HOST: ssh.strato.com
          USER: staijen.eu
          PASS: ${{ secrets.SFTP_PASSWORD }}
        run: |
          lftp -e "
          set sftp:auto-confirm yes;
          open sftp://$USER:$PASS@$HOST;
          mirror -R ./ /staijen;
          bye
          "
         